name: "Deploy"

on:
  push:
    branches: [main]

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      GOOGLE_BACKEND_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      TF_VAR_gcp_project: ${{ secrets.GCP_PROJECT }}
      TF_VAR_cloudsql_user: ${{ secrets.GCP_CLOUD_SQL_USER }}
      TF_VAR_cloudsql_password: ${{ secrets.GCP_CLOUD_SQL_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            terraform:
              - 'terraform/**'

      - name: Setup Terraform
        if: steps.changes.outputs.terraform == 'true'
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        if: steps.changes.outputs.terraform == 'true'
        run: |
          terraform init \
            -backend-config bucket=${{ secrets.TF_BACKEND_BUCKET }}
        working-directory: terraform

      - name: Terraform Plan
        if: steps.changes.outputs.terraform == 'true'
        run: terraform plan
        working-directory: terraform

      - name: Terraform Apply
        if: steps.changes.outputs.terraform == 'true'
        run: terraform apply -auto-approve
        working-directory: terraform
